=== Leo030891/electron-exam/static/schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": ["title", "code", "group", "time", "pass", "cover", "test"],
  "properties": {
    "title": {
      "$id": "#/properties/title",
      "type": "string",
      "title": "The Title Schema",
      "default": "",
      "examples": ["Oracle Database"],
      "pattern": "^(.*)$"
    },
    "code": {
      "$id": "#/properties/code",
      "type": "string",
      "title": "The Code Schema",
      "default": "",
      "examples": ["1z0-061"],
      "pattern": "^(.*)$"
    },
    "group": {
      "$id": "#/properties/group",
      "type": "string",
      "title": "The Group Schema",
      "default": "",
      "examples": [""],
      "pattern": "^(.*)$"
    },
    "time": {
      "$id": "#/properties/time",
      "type": "integer",
      "title": "The Time Schema",
      "default": 0,
      "examples": [120]
    },
    "pass": {
      "$id": "#/properties/pass",
      "type": "integer",
      "title": "The Pass Schema",
      "default": 0,
      "examples": [65]
    },
    "cover": {
      "$id": "#/properties/cover",
      "type": "array",
      "title": "The Cover Schema",
      "items": {
        "$id": "#/properties/cover/items",
        "type": "object",
        "title": "The Items Schema",
        "required": ["type", "text"],
        "properties": {
          "type": {
            "$id": "#/properties/cover/items/properties/type",
            "type": "integer",
            "title": "The Type Schema",
            "default": 0,
            "examples": [0]
          },
          "text": {
            "$id": "#/properties/cover/items/properties/text",
            "type": "string",
            "title": "The Text Schema",
            "default": "",
            "examples": [
              "https://www.oracle.com/webfolder/s/brand/assets/i/specimens/identity/logo/primary-sig.gif"
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    },
    "test": {
      "$id": "#/properties/test",
      "type": "array",
      "title": "The Test Schema",
      "items": {
        "$id": "#/properties/test/items",
        "type": "object",
        "title": "The Items Schema",
        "required": ["type", "question", "choices", "answer", "explanation"],
        "properties": {
          "type": {
            "$id": "#/properties/test/items/properties/type",
            "type": "integer",
            "title": "The Type Schema",
            "default": 0,
            "examples": [1]
          },
          "question": {
            "$id": "#/properties/test/items/properties/question",
            "type": "array",
            "title": "The Question Schema",
            "items": {
              "$id": "#/properties/test/items/properties/question/items",
              "type": "object",
              "title": "The Items Schema",
              "required": ["type", "text"],
              "properties": {
                "type": {
                  "$id": "#/properties/test/items/properties/question/items/properties/type",
                  "type": "integer",
                  "title": "The Type Schema",
                  "default": 0,
                  "examples": [1]
                },
                "text": {
                  "$id": "#/properties/test/items/properties/question/items/properties/text",
                  "type": "string",
                  "title": "The Text Schema",
                  "default": "",
                  "examples": [
                    "Which three tasks can be performed using SQL functions built into Oracle Database?"
                  ],
                  "pattern": "^(.*)$"
                }
              }
            }
          },
          "choices": {
            "$id": "#/properties/test/items/properties/choices",
            "type": "array",
            "title": "The Choices Schema",
            "items": {
              "$id": "#/properties/test/items/properties/choices/items",
              "type": "object",
              "title": "The Items Schema",
              "required": ["label", "text"],
              "properties": {
                "label": {
                  "$id": "#/properties/test/items/properties/choices/items/properties/label",
                  "type": "string",
                  "title": "The Label Schema",
                  "default": "",
                  "examples": ["A"],
                  "pattern": "^(.*)$"
                },
                "text": {
                  "$id": "#/properties/test/items/properties/choices/items/properties/text",
                  "type": "string",
                  "title": "The Text Schema",
                  "default": "",
                  "examples": ["Displaying a date in nondefault format"],
                  "pattern": "^(.*)$"
                }
              }
            }
          },
          "answer": {
            "$id": "#/properties/test/items/properties/answer",
            "type": "array",
            "title": "The Answer Schema",
            "items": {
              "$id": "#/properties/test/items/properties/answer/items",
              "type": "boolean",
              "title": "The Items Schema",
              "default": false,
              "examples": [true, true, true, false]
            }
          },
          "explanation": {
            "$id": "#/properties/test/items/properties/explanation",
            "type": "array",
            "title": "The Explanation Schema"
          }
        }
      }
    }
  }
}

=== Leo030891/electron-exam/static/exams/copy-cat.json
{
  "title": "Oracle Database",
  "code": "1z0-061",
  "group": "",
  "time": 120,
  "pass": 65,
  "cover": [
    {
      "type": 0,
      "text": "https://www.oracle.com/webfolder/s/brand/assets/i/specimens/identity/logo/primary-sig.gif"
    },
    {
      "type": 1,
      "text": "Oracle 1z0-061 Database Fundamentals"
    }
  ],
  "test": [
    {
      "type": 1,
      "question": [
        {
          "type": 1,
          "text": "Which three tasks can be performed using SQL functions built into Oracle Database?"
        }
      ],
      "choices": [
        {
          "label": "A",
          "text": "Displaying a date in nondefault format"
        },
        {
          "label": "B",
          "text": "Finding the number of characters in an expression"
        },
        {
          "label": "C",
          "text": "Substituting a character string in a text expression with a specified string"
        },
        {
          "label": "D",
          "text": "Combining more than two columns or expressions into a single column in the output"
        }
      ],
      "answer": [true, true, true, false],
      "explanation": []
    },
    {
      "type": 1,
      "question": [
        {
          "type": 1,
          "text": "View the Exhibit and examine the description of SALES and PROMOTIONS tables."
        },
        {
          "type": 0,
          "text": "https://s3.amazonaws.com/electron-exam/oracle-1z0-061/2e.PNG"
        },
        {
          "type": 1,
          "text": "You want to delete rows from the sales table, where the PROMO_NAME column in the promotions table has either blowout sale or everyday low prices as values."
        },
        {
          "type": 1,
          "text": "Which three delete statements are valid?"
        },
        {
          "type": 0,
          "text": "https://s3.amazonaws.com/electron-exam/oracle-1z0-061/2a.PNG"
        }
      ],
      "choices": [
        {
          "label": "A",
          "text": "Option A"
        },
        {
          "label": "B",
          "text": "Option B"
        },
        {
          "label": "C",
          "text": "Option C"
        },
        {
          "label": "D",
          "text": "Option D"
        }
      ],
      "answer": [false, true, true, true],
      "explanation": []
    },
    {
      "type": 1,
      "question": [
        {
          "type": 1,
          "text": "Which three SQL statements would display the value 1890.55 as $1,890.55?"
        },
        {
          "type": 0,
          "text": "https://s3.amazonaws.com/electron-exam/oracle-1z0-061/3a.PNG"
        }
      ],
      "choices": [
        {
          "label": "A",
          "text": "Option A"
        },
        {
          "label": "B",
          "text": "Option B"
        },
        {
          "label": "C",
          "text": "Option C"
        },
        {
          "label": "D",
          "text": "Option D"
        },
        {
          "label": "E",
          "text": "Option E"
        }
      ],
      "answer": [true, false, false, true, true],
      "explanation": []
    },
    {
      "type": 0,
      "question": [
        {
          "type": 1,
          "text": "You want to display 5 percent of the employees with the highest salaries in the EMPLOYEES table."
        },
        {
          "type": 1,
          "text": "Which query will generate the required result?"
        },
        {
          "type": 0,
          "text": "https://s3.amazonaws.com/electron-exam/oracle-1z0-061/4a.PNG"
        }
      ],
      "choices": [
        {
          "label": "A",
          "text": "Option A"
        },
        {
          "label": "B",
          "text": "Option B"
        },
        {
          "label": "C",
          "text": "Option C"
        },
        {
          "label": "D",
          "text": "Option D"
        }
      ],
      "answer": [false, true, false, false],
      "explanation": []
    },
    {
      "type": 0,
      "question": [
        {
          "type": 1,
          "text": "In the customers table, the CUST_CITY column contains the value 'Paris' for the CUST_FIRST_NAME 'Abigail'."
        },
        {
          "type": 1,
          "text": "Evaluate the following query:"
        },
        {
          "type": 0,
          "text": "https://s3.amazonaws.com/electron-exam/oracle-1z0-061/5e.PNG"
        },
        {
          "type": 1,
          "text": "What would be the outcome?"
        }
      ],
      "choices": [
        {
          "label": "A",
          "text": "Abigail PA"
        },
        {
          "label": "B",
          "text": "Abigail Pa"
        },
        {
          "label": "C",
          "text": "Abigail IS"
        },
        {
          "label": "D",
          "text": "An error message"
        }
      ],
      "answer": [false, true, false, false],
      "explanation": []
    },
    {
      "type": 0,
      "question": [
        {
          "type": 1,
          "text": "View the Exhibit and evaluate the structure and data in the CUST_STATUS table."
        },
        {
          "type": 0,
          "text": "https://s3.amazonaws.com/electron-exam/oracle-1z0-061/6e1.PNG"
        },
        {
          "type": 1,
          "text": "You issue the following SQL statement:"
        },
        {
          "type": 0,
          "text": "https://s3.amazonaws.com/electron-exam/oracle-1z0-061/6e2.PNG"
        },
        {
          "type": 1,
          "text": "Which statement is true regarding the execution of the above query?"
        }
      ],
      "choices": [
        {
          "label": "A",
          "text": "It produces an error because the AMT_SPENT column contains a null value."
        },
        {
          "label": "B",
          "text": "It displays a bonus of 1000 for all customers whose AMT_SPENT is less than CREDIT_LIMIT."
        },
        {
          "label": "C",
          "text": "It displays a bonus of 1000 for all customers whose AMT_SPENT equals CREDIT_LIMIT, or AMT_SPENT is null."
        },
        {
          "label": "D",
          "text": "It produces an error because the TO_NUMBER function must be used to convert the result of the NULLIF function before it can be used by the NVL2 function."
        }
      ],
      "answer": [false, false, true, false],
      "explanation": []
    }
  ]
}
